name: gen_doc

on:
  workflow_dispatch:

jobs:
  gen_doc:
    name: gen_doc
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Config git 
      run: |
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
    - uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: './Doxyfile'

    - name: Create gh-pages branch
      run: |
        git branch -d gh-pages &> /dev/null || echo gh-pages branch not found
        
        git checkout --orphan gh-pages
        
        find . -maxdepth 1 ! -name "docs" ! -name ".*" -print0 | xargs -0 rm -rf
        
        git commit -am "docs: remove all"
        
        git add docs/*
        git commit -m "docs: generate doxygen"
        
        git push -f -u origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
